export const CATALOG_CURRENCY = "KES" as const;

export type InitialCatalogProduct = {
  catalogKey: string;
  slug: string;
  name: string;
  category: string;
  description: string;
  priceMinor: bigint;
  currency: typeof CATALOG_CURRENCY;
  sortOrder: number;
};

const product = (
  catalogKey: string,
  slug: string,
  name: string,
  category: string,
  description: string,
  priceMinor: bigint,
  sortOrder: number,
): InitialCatalogProduct => ({
  catalogKey,
  slug,
  name,
  category,
  description,
  priceMinor,
  currency: CATALOG_CURRENCY,
  sortOrder,
});

export const INITIAL_CATALOG = [
  product(
    "lp-01",
    "hp-elitebook-840-g8-i7-16gb-512gb",
    "HP EliteBook 840 G8 · i7 16GB/512GB",
    "Laptops",
    'Business ultrabook, backlit keyboard, 14" FHD.',
    7_850_000n,
    0,
  ),
  product(
    "lp-02",
    "dell-latitude-5420-i5-8gb-256gb",
    "Dell Latitude 5420 · i5 8GB/256GB",
    "Laptops",
    "Reliable daily driver for school and office.",
    5_200_000n,
    1,
  ),
  product(
    "lp-03",
    "lenovo-thinkpad-x1-carbon-gen-9",
    "Lenovo ThinkPad X1 Carbon Gen 9",
    "Laptops",
    "Carbon-fibre flagship, 1.1kg, 16GB RAM.",
    11_800_000n,
    2,
  ),
  product(
    "lp-04",
    "macbook-air-m2-8gb-256gb",
    "MacBook Air M2 · 8GB/256GB",
    "Laptops",
    "All-day battery, silent fanless design.",
    15_200_000n,
    3,
  ),
  product(
    "sc-01",
    "samsung-55-crystal-uhd-4k-smart-tv",
    'Samsung 55" Crystal UHD 4K Smart TV',
    "Screens",
    "HDR10+, Tizen apps, voice remote.",
    6_290_000n,
    4,
  ),
  product(
    "sc-02",
    "lg-ultragear-27-165hz-gaming-monitor",
    'LG UltraGear 27" 165Hz Gaming Monitor',
    "Screens",
    "1ms IPS, G-Sync compatible, height adjust.",
    4_150_000n,
    5,
  ),
  product(
    "sc-03",
    "dell-p2422h-24-ips-office-monitor",
    'Dell P2422H 24" IPS Office Monitor',
    "Screens",
    "Flicker-free, pivot stand, HDMI + DP.",
    2_390_000n,
    6,
  ),
  product(
    "sc-04",
    "hisense-43-smart-frameless-tv",
    'Hisense 43" Smart Frameless TV',
    "Screens",
    "Netflix & YouTube built in, bezel-less.",
    3_480_000n,
    7,
  ),
  product(
    "wf-01",
    "jbl-bar-5-1-soundbar-wireless-woofer",
    "JBL Bar 5.1 Soundbar + Wireless Woofer",
    "Woofers",
    "550W, detachable surround speakers.",
    8_900_000n,
    8,
  ),
  product(
    "wf-02",
    "sony-sa-sw3-200w-active-subwoofer",
    "Sony SA-SW3 200W Active Subwoofer",
    "Woofers",
    "Deep bass module for home theatre.",
    4_650_000n,
    9,
  ),
  product(
    "wf-03",
    "vitron-3-1ch-home-theatre-woofer",
    "Vitron 3.1CH Home Theatre Woofer",
    "Woofers",
    "Bluetooth, USB, FM — the estate favourite.",
    1_890_000n,
    10,
  ),
  product(
    "wf-04",
    "edifier-r1280db-studio-monitors",
    "Edifier R1280DB Studio Monitors",
    "Woofers",
    "Bookshelf pair with optical + Bluetooth.",
    2_140_000n,
    11,
  ),
  product(
    "ac-01",
    "anker-65w-gan-charger-usb-c-cable",
    "Anker 65W GaN Charger + USB-C Cable",
    "Accessories",
    "Charges laptop and phone from one brick.",
    490_000n,
    12,
  ),
  product(
    "ac-02",
    "logitech-mx-keys-s-wireless-keyboard",
    "Logitech MX Keys S Wireless Keyboard",
    "Accessories",
    "Backlit, multi-device, USB-C.",
    1_350_000n,
    13,
  ),
  product(
    "ac-03",
    "1500va-line-interactive-ups",
    "1500VA Line-Interactive UPS",
    "Accessories",
    "Keeps the shop running through blackouts.",
    1_680_000n,
    14,
  ),
  product(
    "ac-04",
    "hdmi-2-1-8k-braided-cable-3m",
    "HDMI 2.1 8K Braided Cable · 3m",
    "Accessories",
    "48Gbps for screens and consoles.",
    230_000n,
    15,
  ),
  product(
    "ph-01",
    "20000mah-fast-power-bank",
    "20000mAh Fast Power Bank",
    "Phones & Tablets",
    "22.5W fast charge, triple output.",
    219_900n,
    16,
  ),
  product(
    "ph-02",
    "smart-6-7-android-phone-128gb",
    'Smart 6.7" Android Phone 128GB',
    "Phones & Tablets",
    "5000mAh battery, 50MP camera.",
    1_849_900n,
    17,
  ),
  product(
    "ph-03",
    "airpulse-wireless-earbuds",
    "AirPulse Wireless Earbuds",
    "Phones & Tablets",
    "ENC calls, 30h case, USB-C.",
    349_900n,
    18,
  ),
  product(
    "ph-04",
    "10-kids-learning-tablet",
    '10" Kids Learning Tablet',
    "Phones & Tablets",
    "Parental controls and a tough case.",
    1_299_900n,
    19,
  ),
  product(
    "hk-01",
    "6l-digital-air-fryer",
    "6L Digital Air Fryer",
    "Home & Kitchen",
    "8 presets, non-stick basket.",
    749_900n,
    20,
  ),
  product(
    "hk-02",
    "non-stick-cookware-set-7pc",
    "Non-Stick Cookware Set · 7pc",
    "Home & Kitchen",
    "Pots, pans and glass lids.",
    489_900n,
    21,
  ),
  product(
    "hk-03",
    "stainless-steel-cutlery-24pc",
    "Stainless Steel Cutlery 24pc",
    "Home & Kitchen",
    "Rust-free family set.",
    189_900n,
    22,
  ),
  product(
    "hk-04",
    "2l-electric-kettle-cordless",
    "2L Electric Kettle · Cordless",
    "Home & Kitchen",
    "Auto shut-off, fast boil.",
    229_900n,
    23,
  ),
  product(
    "fa-01",
    "men-s-classic-polo-shirt",
    "Men's Classic Polo Shirt",
    "Fashion",
    "Breathable cotton pique.",
    129_900n,
    24,
  ),
  product(
    "fa-02",
    "urban-canvas-sneakers",
    "Urban Canvas Sneakers",
    "Fashion",
    "Everyday street sneakers.",
    329_900n,
    25,
  ),
  product(
    "fa-03",
    "ladies-ankara-maxi-dress",
    "Ladies Ankara Maxi Dress",
    "Fashion",
    "Vibrant print, all sizes.",
    249_900n,
    26,
  ),
  product(
    "fa-04",
    "minimalist-steel-watch",
    "Minimalist Steel Watch",
    "Fashion",
    "Sapphire-look glass, 3ATM.",
    289_900n,
    27,
  ),
  product(
    "bh-01",
    "vitamin-c-brightening-serum",
    "Vitamin C Brightening Serum",
    "Beauty & Health",
    "30ml, hyaluronic blend.",
    149_900n,
    28,
  ),
  product(
    "bh-02",
    "shea-and-argan-body-butter",
    "Shea & Argan Body Butter",
    "Beauty & Health",
    "Deep moisture, natural.",
    99_900n,
    29,
  ),
  product(
    "bh-03",
    "digital-bathroom-scale",
    "Digital Bathroom Scale",
    "Beauty & Health",
    "Tempered glass, 180kg.",
    179_900n,
    30,
  ),
  product(
    "bh-04",
    "rechargeable-hair-clipper",
    "Rechargeable Hair Clipper",
    "Beauty & Health",
    "Cordless, 8 guards.",
    245_000n,
    31,
  ),
  product(
    "so-01",
    "school-backpack-waterproof",
    "School Backpack · Waterproof",
    "School & Office",
    "Padded laptop sleeve.",
    165_000n,
    32,
  ),
  product(
    "so-02",
    "a4-exercise-books-10-pack",
    "A4 Exercise Books · 10 pack",
    "School & Office",
    "200 pages, squared or ruled.",
    78_000n,
    33,
  ),
  product(
    "so-03",
    "scientific-calculator-fx-991",
    "Scientific Calculator FX-991",
    "School & Office",
    "417 functions, exam ready.",
    145_000n,
    34,
  ),
  product(
    "so-04",
    "office-desk-organiser-set",
    "Office Desk Organiser Set",
    "School & Office",
    "Trays, pen pots and file rack.",
    125_000n,
    35,
  ),
  product(
    "gr-01",
    "premium-aa-arabica-coffee-1kg",
    "Premium AA Arabica Coffee 1kg",
    "Groceries",
    "Roasted beans, Kenyan grown.",
    189_900n,
    36,
  ),
  product(
    "gr-02",
    "sunflower-cooking-oil-5l",
    "Sunflower Cooking Oil 5L",
    "Groceries",
    "Cholesterol free, family size.",
    145_000n,
    37,
  ),
  product(
    "gr-03",
    "long-grain-pishori-rice-5kg",
    "Long Grain Pishori Rice 5kg",
    "Groceries",
    "Aromatic Mwea rice.",
    129_000n,
    38,
  ),
  product(
    "gr-04",
    "assorted-spice-rack-12-jars",
    "Assorted Spice Rack 12 jars",
    "Groceries",
    "Everyday kitchen spices.",
    115_000n,
    39,
  ),
  product(
    "sp-01",
    "adjustable-dumbbell-set-20kg",
    "Adjustable Dumbbell Set 20kg",
    "Sports & Outdoors",
    "Home gym starter kit.",
    690_000n,
    40,
  ),
  product(
    "sp-02",
    "size-5-match-football",
    "Size 5 Match Football",
    "Sports & Outdoors",
    "Hand-stitched, all surfaces.",
    135_000n,
    41,
  ),
  product(
    "sp-03",
    "6mm-yoga-mat-strap",
    "6mm Yoga Mat + Strap",
    "Sports & Outdoors",
    "Non-slip, easy to roll.",
    169_000n,
    42,
  ),
  product(
    "sp-04",
    "4-person-camping-tent",
    "4-Person Camping Tent",
    "Sports & Outdoors",
    "Waterproof, quick pitch.",
    780_000n,
    43,
  ),
] as const satisfies readonly InitialCatalogProduct[];

export const CATALOG_CATEGORIES = [...new Set(INITIAL_CATALOG.map((item) => item.category))];
